version: 2.1

orbs:
  gem: goldstar/publish-gem@1.3.0

workflows:
  main:
    jobs:
      - gem/test:
          executor_type:
            name: gem/ruby_redis
            exec_ruby_version: 2.6.6
            exec_redis_version: 5.0-alpine
      - gem/build-and-deploy:
          context: packagecloud
          requires:
            - gem/test
          filters:
            branches:
              only: master
          packagecloud-repo: goldstar/production

