
version: 2.1

orbs:
  gem: goldstar/publish-gem@1.1.0

workflows:
  main:
    jobs:
      - gem/test
      - gem/build-and-deploy:
          context: packagecloud
          requires:
            - gem/test
          filters:
            branches:
              only: master
          packagecloud-repo: goldstar/production
